version: "3.7"
services:
  php:
    container_name: test-php
    build:
      context: ./
      dockerfile: ./Dockerfile
    environment:
      - DOCKER=1
    volumes:
      - .:/var/www

  webserver:
    image: nginx:latest
    container_name: test-nginx
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
      - ./docker/config/default.conf:/etc/nginx/conf.d/default.conf
